services:
  - type: web
    name: ny-health-act-contact-helper
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /healthz
    autoDeploy: true
